server:
  port: 8000
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/custom"
    username: postgres
    password: Admin@123
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/custom
  web:
    cors:
      allowed-origins: "http://localhost:4200"
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      allow-credentials: true
keycloak:
  auth-server-url: http://localhost:8080
  realm: custom
  resource: custom
  public-client: true
  bearer-only: true

camunda:
  bpm:
#    database-history: full
#    enforce-ttl: false
#    history-level: full
#    history-time-to-live: 30d
    engine:
      name: default
    rest-enabled: true
    auto-deployment-enabled: true
    default-serializer-format: application/json
    authorization:
      enabled: false
    admin-user:
      id: admin
      password: 123
    database:
      type: postgres
    webapp:
      index-redirect-enabled: true
    job-execution:
      enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html